-- users 表资料扩展（增量迁移）
-- 请先 USE 你的业务库（与 .env 中 MYSQL_DATABASE 一致），再执行本文件

SET NAMES utf8mb4;

ALTER TABLE users ADD COLUMN email VARCHAR(191) NULL DEFAULT NULL AFTER display_name;
ALTER TABLE users ADD COLUMN bio TEXT NULL AFTER email;
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(500) NULL DEFAULT NULL AFTER bio;
ALTER TABLE users ADD COLUMN github_url VARCHAR(500) NULL DEFAULT NULL AFTER avatar_url;
ALTER TABLE users ADD COLUMN gitee_url VARCHAR(500) NULL DEFAULT NULL AFTER github_url;
ALTER TABLE users ADD COLUMN website_url VARCHAR(500) NULL DEFAULT NULL AFTER gitee_url;
ALTER TABLE users ADD COLUMN password_changed_at DATETIME(3) NULL DEFAULT NULL AFTER last_login_at;

ALTER TABLE users
  ADD UNIQUE KEY uk_users_email (email);
